<?php

namespace Database\Seeders;

use App\Enums\LeadStatus;
use App\Enums\TaskPriority;
use App\Enums\TaskStatus;
use App\Models\Customer;
use App\Models\Lead;
use App\Models\User;
use App\Services\CustomerService;
use App\Services\LeadService;
use App\Services\TaskService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

/**
 * Seeds realistic CRM demo data (leads, customers, tasks, notes) on top of
 * the three demo users created by DemoUserSeeder.
 *
 * Activities are intentionally NOT inserted directly: every entity below is
 * created through the same LeadService/CustomerService/TaskService used by
 * the controllers, so activity rows are generated by the app's normal
 * ActivityService::log() calls exactly as they would be for real usage.
 */
class DemoDataSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('email', 'admin@example.com')->first();
        $manager = User::where('email', 'manager@example.com')->first();
        $executive = User::where('email', 'executive@example.com')->first();

        if (! $admin || ! $manager || ! $executive) {
            $this->command?->warn('DemoDataSeeder skipped: demo users not found. Run DemoUserSeeder first.');

            return;
        }

        $users = [$admin, $manager, $executive];

        // Idempotency guard: if these users already own seeded leads, assume
        // this seeder already ran against the current database and bail out.
        if (Lead::query()->whereIn('created_by', collect($users)->pluck('id'))->exists()) {
            $this->command?->info('DemoDataSeeder skipped: demo data already present.');

            return;
        }

        $leadService = app(LeadService::class);
        $customerService = app(CustomerService::class);
        $taskService = app(TaskService::class);

        $leads = $this->seedLeads($leadService, $users);

        $customers = $this->seedCustomers($customerService, $leads, $users);

        $this->seedTasks($taskService, $leads, $customers, $users);

        $this->seedNotes($customerService, $customers, $users);
    }

    /**
     * @param  array<int, User>  $users
     * @return array<int, Lead>
     */
    private function seedLeads(LeadService $leadService, array $users): array
    {
        $statusCounts = [
            LeadStatus::NEW->value => 15,
            LeadStatus::CONTACTED->value => 10,
            LeadStatus::QUALIFIED->value => 10,
            LeadStatus::PROPOSAL_SENT->value => 5,
            LeadStatus::WON->value => 5,
            LeadStatus::LOST->value => 5,
        ];

        $statuses = [];
        foreach ($statusCounts as $status => $count) {
            $statuses = array_merge($statuses, array_fill(0, $count, $status));
        }
        shuffle($statuses);

        $sources = ['website', 'referral', 'cold-call', 'event', 'advertisement'];

        return DB::transaction(function () use ($statuses, $sources, $users, $leadService) {
            $leads = [];

            foreach ($statuses as $i => $status) {
                $creator = $users[$i % count($users)];
                $assignee = $users[($i + 1) % count($users)];

                $leads[] = $leadService->create([
                    'assigned_to' => $assignee->id,
                    'first_name' => fake()->firstName(),
                    'last_name' => fake()->lastName(),
                    'email' => fake()->unique()->safeEmail(),
                    'phone' => fake()->phoneNumber(),
                    'company' => fake()->company(),
                    'status' => $status,
                    'source' => fake()->randomElement($sources),
                ], $creator);
            }

            return $leads;
        });
    }

    /**
     * Convert a random subset of non-lost leads into customers, preserving
     * the underlying lead record. CustomerService::convertLead marks the
     * source lead as WON as part of conversion, which is the app's standard
     * "won" flow.
     *
     * @param  array<int, Lead>  $leads
     * @param  array<int, User>  $users
     * @return array<int, Customer>
     */
    private function seedCustomers(CustomerService $customerService, array $leads, array $users): array
    {
        $eligible = array_values(array_filter($leads, fn (Lead $lead) => $lead->status !== LeadStatus::LOST));
        shuffle($eligible);

        $convertCount = min(count($eligible), random_int(15, 20));
        $toConvert = array_slice($eligible, 0, $convertCount);

        return DB::transaction(function () use ($toConvert, $users, $customerService) {
            $customers = [];

            foreach ($toConvert as $i => $lead) {
                try {
                    $customers[] = $customerService->convertLead($lead, $users[$i % count($users)]);
                } catch (ValidationException) {
                    // Lead already converted; skip.
                }
            }

            return $customers;
        });
    }

    /**
     * @param  array<int, Lead>  $leads
     * @param  array<int, Customer>  $customers
     * @param  array<int, User>  $users
     */
    private function seedTasks(TaskService $taskService, array $leads, array $customers, array $users): void
    {
        $statuses = [TaskStatus::PENDING->value, TaskStatus::IN_PROGRESS->value, TaskStatus::COMPLETED->value];
        $priorities = [TaskPriority::LOW->value, TaskPriority::MEDIUM->value, TaskPriority::HIGH->value];
        $dueDateOffsets = [-7, -3, -1, 0, 0, 3, 7, 14]; // overdue, today, future mix

        $titles = [
            'Follow up call', 'Send proposal', 'Schedule demo', 'Review contract',
            'Check in with customer', 'Prepare quote', 'Discovery call', 'Send onboarding docs',
        ];

        DB::transaction(function () use ($statuses, $priorities, $dueDateOffsets, $titles, $leads, $customers, $users, $taskService) {
            for ($i = 0; $i < 50; $i++) {
                $linkToCustomer = ! empty($customers) && ($i % 2 === 0 || empty($leads));
                $leadId = null;
                $customerId = null;

                if ($linkToCustomer) {
                    $customerId = fake()->randomElement($customers)->id;
                } else {
                    $leadId = fake()->randomElement($leads)->id;
                }

                $offset = fake()->randomElement($dueDateOffsets);

                $taskService->create([
                    'user_id' => $users[$i % count($users)]->id,
                    'customer_id' => $customerId,
                    'lead_id' => $leadId,
                    'title' => fake()->randomElement($titles),
                    'description' => fake()->sentence(),
                    'priority' => $priorities[$i % count($priorities)],
                    'status' => $statuses[$i % count($statuses)],
                    'due_date' => now()->addDays($offset)->toDateString(),
                ], $users[$i % count($users)]);
            }
        });
    }

    /**
     * @param  array<int, Customer>  $customers
     * @param  array<int, User>  $users
     */
    private function seedNotes(CustomerService $customerService, array $customers, array $users): void
    {
        DB::transaction(function () use ($customers, $users, $customerService) {
            foreach ($customers as $customer) {
                $noteCount = random_int(3, 5);

                for ($i = 0; $i < $noteCount; $i++) {
                    $author = fake()->randomElement($users);

                    $customerService->addNote($customer, [
                        'note' => fake()->paragraph(),
                    ], $author);
                }
            }
        });
    }
}
